name: 'Git versioning'
description: 'Versioning from git tags with conventional commit bump'
inputs:
  tag-prefix:  # id of input
    description: 'tag prefix, default v'
    required: false
    default: 'v'
  # tag-commit:
  #   description: 'tag the upcomming version'
  #   required: false
  #   default: false
outputs:
  currentVersion: # id of output
    description: 'the version found in git'
  currentTag:
    description: 'the tag found in git'
  nextVersion:
    description: 'the upcomming version'
  nextTag:
    description: 'upcomming tag name'
runs:
  using: 'node12'
  main: 'dist/index.js'